<?php

namespace ContainerXp4QdXo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CompanyType' shared autowired service.
     *
     * @return \App\Form\CompanyType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CompanyType.php';

        return $container->privates['App\\Form\\CompanyType'] = new \App\Form\CompanyType();
    }
}
