<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXwb43IF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXwb43IF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXwb43IF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXwb43IF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXwb43IF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xwb43IF',
    'container.build_id' => 'b39bb90c',
    'container.build_time' => 1695806677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXwb43IF');
