<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'shop' => [[], ['_controller' => 'App\\Controller\\ShopController::index'], [], [['text', '/shop']], [], [], []],
    'basket' => [[], ['_controller' => 'App\\Controller\\BasketController::index'], [], [['text', '/basket']], [], [], []],
    'product' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product']], [], [], []],
    'create-product' => [[], ['_controller' => 'App\\Controller\\ProductController::createProduct'], [], [['text', '/create-product']], [], [], []],
    'edit-product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::editProduct'], [], [['variable', '', '[^/]++', 'id', true], ['text', '/edit-product']], [], [], []],
    'delete-product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::deleteProduct'], [], [['variable', '', '[^/]++', 'id', true], ['text', '/delete-product']], [], [], []],
    'create-category' => [[], ['_controller' => 'App\\Controller\\ProductPropertiesController::createCategory'], [], [['text', '/create-category']], [], [], []],
    'create-company' => [[], ['_controller' => 'App\\Controller\\ProductPropertiesController::createCompany'], [], [['text', '/create-company']], [], [], []],
    'create-region' => [[], ['_controller' => 'App\\Controller\\ProductPropertiesController::createRegion'], [], [['text', '/create-region']], [], [], []],
    'create-vine-grape' => [[], ['_controller' => 'App\\Controller\\ProductPropertiesController::createVineGrape'], [], [['text', '/create-vine-grape']], [], [], []],
];
